// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSite.Models;

namespace WebSite.Migrations
{
    [DbContext(typeof(UnitContext))]
    [Migration("20181201074103_Initialcreate")]
    partial class Initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("WebSite.Models.AdvertisementInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdvertisementContent");

                    b.Property<string>("AdvertisementUrl");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("ImgPath");

                    b.Property<string>("Name");

                    b.Property<string>("Remarks");

                    b.Property<int>("State");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.ToTable("AdvertisementInfos");
                });

            modelBuilder.Entity("WebSite.Models.ContentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClickNum");

                    b.Property<string>("Content");

                    b.Property<string>("CreateTime");

                    b.Property<int>("CreateUserId");

                    b.Property<string>("PreviewImgPath");

                    b.Property<int>("RecommendNum");

                    b.Property<string>("Remarks");

                    b.Property<int>("State");

                    b.Property<string>("Title");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.ToTable("ContentInfos");
                });

            modelBuilder.Entity("WebSite.Models.FileInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<string>("Remarks");

                    b.Property<DateTime>("UploadTime");

                    b.HasKey("Id");

                    b.ToTable("FileInfos");
                });

            modelBuilder.Entity("WebSite.Models.TypeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("ParentId");

                    b.Property<string>("Remarks");

                    b.Property<string>("TypeName");

                    b.HasKey("Id");

                    b.ToTable("TypeInfos");
                });

            modelBuilder.Entity("WebSite.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("HeadImgPath");

                    b.Property<int>("State");

                    b.Property<string>("UserName");

                    b.Property<string>("UserPwd");

                    b.HasKey("Id");

                    b.ToTable("UserInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
